### ISSUE TITLE
chanop can KICK itself out

### ISSUE THREAD

**Issue by Bee-Have** [Bee-Have/ft_irc_duck#62]
need #1 to be implemented before.

If a chanop uses the KICK command on itself, it will work.

This is problematic because currently, chanop privilege is not transferred.

BUT, do we want a chanop to be able to KICK itself out ?
If so, should we call PART instead ? Since it is technically what's happening ?

If not do we implement a new ERR_ for it ? Or simply ignore this entry ?

**Comment by NotCampeur** [comment]
This behavior has been tester on GameSurge irc server with IRSSI.
Channel operator can kick itself out and rights are effectively not transferred.
We will carry on with this behavior as it has been encountered in the wild.
